[build]
  publish = "out"
  command = "rm -rf .next out node_modules/.cache && npm ci && npm run build"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[functions]
  directory = "netlify/functions/"