[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  # Enable Next.js static export in next.config when building on Netlify
  NETLIFY = "true"
  NODE_VERSION = "18"

[functions]
  # Functions live at repo-root netlify/functions
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
