[build]
  base = "frontend"
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Ensure proper MIME types for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"