name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: codex_refac/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (lean for tests)
        run: |
          python -m pip install --upgrade pip
          pip install fastapi==0.116.1 pydantic==2.11.7 httpx pytest pytest-asyncio
      - name: Run tests
        env:
          FAST_TEST: '1'
          ENABLE_EDUCATIONAL_MCP: '0'
        run: pytest -q

